import { ThirdwebWeb3Provider } from '@3rdweb/hooks'
import './globals.css'

const supportedChainIds = [5]
const connectors = { injected: {} }

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<ThirdwebWeb3Provider
			supportedChainIds={supportedChainIds}
			connectors={connectors}
		>
			<body className={inter.className}>{children}</body>
		</ThirdwebWeb3Provider>
	)
}
